name: Build client image
on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        arch: ["amd64"]
        docker: ["client"]
      fail-fast: false
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: nvcr.io
          username: $oauthtoken
          password: ${{ secrets.DOCKER_NVIDIA }}
      - uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.docker }}
          labels: |
            org.opencontainers.image.title=${{ github.repository }}/${{ matrix.docker }}
        id: docker
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.${{ matrix.docker }}
          tags: ${{ steps.docker.outputs.tags }}
          labels: ${{ steps.docker.outputs.labels }}
          platforms: linux/${{ matrix.arch }}
          push: true
