name: Create and publish Docker image

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@1f401f745bf57e30b3a2800ad308a87d2ebdf14b
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@e6428a5c4e294a61438ed7f43155db912025b6b3
        with:
          images: ghcr.io/${{ github.repository }}/docker
        id: docker
      - uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          context: .
          file: docker/Dockerfile.docker
          push: true
          tags: ${{ steps.docker.outputs.tags }}
          labels: ${{ steps.docker.outputs.labels }}
          platforms: linux/amd64,linux/arm64
