name: Create and publish Docker image
on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - master
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/docker
          labels: |
            org.opencontainers.image.title=docker
        id: docker
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.docker
          push: true
          tags: ${{ steps.docker.outputs.tags }}
          labels: ${{ steps.docker.outputs.labels }}
          platforms: linux/amd64,linux/arm64
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'vision.yml',
              ref: 'master',
            })
