name: Create and publish Python image

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@1f401f745bf57e30b3a2800ad308a87d2ebdf14b
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@62339db73c56dd749060f65a6ebb93a6e056b755
        with:
          images: ghcr.io/${{ github.repository }}/python
        id: python
      - uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56
        with:
          context: .
          file: docker/Dockerfile.python
          push: true
          tags: ${{ steps.python.outputs.tags }}
          labels: ${{ steps.python.outputs.labels }}
          platforms: linux/amd64,linux/arm64
